name: py

on:
  push:
    branches:
      - main
    tags:
      - 'jobs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install wandb
          wandb login ${{ secrets.WANDB_API_KEY }}
      - name: Create WANDB job # at this point we could deploy with wandb job create code, which would deploy with this version, however it then wouldn't link back to the Github branch on W&B which is really handy.
        run: |
          git config credential.helper '!f() { echo username=dead-water; echo "password=${{ secrets.PAT_GITHUB_READONLY_THIS_REPO }}"; };f'
          wandb job create --project "${{ secrets.WANDB_PROJECT }}" --entity "${{ secrets.WANDB_ORG }}" --name "gha-${{ github.ref_name }}" git https://github.com/spaceml-org/SDO-FM.git -g launch-testing --entry-point "scripts/test.py"
